### ISSUE TITLE
Subscription inside a controller gets stopped when using "requireUser"

### ISSUE THREAD

**Issue by perttuim** [Urigo/angular-meteor-auth#8] opened 2016-03-14 14:25 UTC
I'm using requireUser function inside UI Router's resolves. Sometimes subscriptions inside the state's controller gets stopped instantly. This happens, oddly, more often when Meteor is run in production mode.

I've tracked the problem to Tracker still being active inside the controller. The computation that keeps it active is the autorun inside the awaitUser function. The subscription then gets it as its parent and is then stopped instantly. The problem goes away when the subscription is started inside a timeout (or the requireUsers's resolve is run inside a timeout).

Here's a short video illustrating the issue: https://youtu.be/swgjlO0E5JM

**Comment by kamilkisiela** [comment] 2016-03-28 14:23
[Reproduction](https://github.com/kamilkisiela/angular-meteor-auth-8)

**Comment by kamilkisiela** [comment] 2016-03-28 17:22
#10 Should fix that

**Comment by Urigo** [comment] 2016-03-28 17:39
Released as `0.2.2` and `1.0.0`
@perttuim can you please confirm that it's fixed for you?
thanks

**Comment by DAB0mB** [comment] 2016-03-28 21:53
@perttuim @kamilkisiela @Urigo The reason why it happens is this. The `$auth` service is just an alias for the `$rootScope`, and any method invoked from it will actually use the `$rootScope` as the context. If you will look closely at `$$Auth.$awaitUser()` you can see that it creates a computation in order to track authentication actions and invoke a promise once the user has been logged in, but it is not an ordinary computation. This computation is bounded to the `$rootScope` and once it is destroyed the computation will be stopped, that's why we use `Scope.autorun()` and not `Tracker.autorun()`. Now that's where the tricky part is, the `$rootScope` is never being destroyed, it lives forever! So any time a child scope is destroyed the computation will stop. This flow causes us the following problems:

- Since we register event listeners on the `$rootScope` which will never be destroyed there is a potential memory leak, because we never remove these listeners. That's why at the previous versions `angular-meteor` methods were not accessible through the `$rootScope` but only the child scopes, to avoid these kinds of problems.
- We stop the computation twice, once inside the computation and once after one of our child scopes has been destroyed, right after we subscribe to our collection, and since the subscription hasn't been activated yet the tracker will stop it and remove it to avoid potential memory leaks. Call it a safety mechanism.

Hope I was clear enough. Anyways I'm working on a fix right now and it shouldn't take too long, so stay tuned :-)

**Comment by perttuim** [comment] 2016-03-29 12:12
@Urigo Seems to be working in 0.2.2!
@DAB0mB Thanks for the great explanation of what's going on.

**Comment by Urigo** [comment] 2016-04-02 10:31
published the new fix as `1.0.1`

**Closed by Urigo** 2016-04-02 10:31 UTC
